import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/nextAuth";
import { SessionProvider } from "next-auth/react";
import AuthContextProvider from "./../lib/AuthContext";

const alexandria = Alexandria({ subsets: ["latin", "arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  console.log(session);

  return (
    <html lang="en">
      <body className={alexandria.className}>
        <AuthContextProvider>
          <Header session={session} />
          {children}
          <Toaster />
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
